### ISSUE TITLE
Odering changed, website text not updated

### ISSUE THREAD

**Issue by WuerfelDev** [bootstrap-vue/bootstrap-vue.github.io#13]
the third box should be first, but it is second?! That's weird. Wrong change in bootstrap-vue or is it wrong text on the webpage?

https://bootstrap-vue.js.org/docs/components/layout#ordering-columns

![image](https://user-images.githubusercontent.com/12686819/59966981-26926380-9524-11e9-8718-395ef8e53288.png)

**Comment by tmorehouse** [comment]
Technically it should be "Thirst, but ordered first".

Un-ordered columns always appear before any columns that are ordered.

**Comment by WuerfelDev** [comment]
Thanks. It isn't clear from the text on the webpage:

Use order-* props for controlling the visual order of your content. These props are responsive, so you can set the order by breakpoint (e.g., order="1" order-md="2"). Includes support for 1 through 12 across all five grid tiers.
