### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by Soviut** [bootstrap-vue/bootstrap-vue.github.io#15]
Navigating to https://bootstrap-vue.js.org/ shows the following error.

![image](https://user-images.githubusercontent.com/226882/79696783-bee49c00-824c-11ea-8084-966edade1ae6.png)

**Comment by jackmu95** [comment]
We are in the process of moving our website to a new hosting provider and currently struggle with DNS related issues. We try to get this sorted out as quickly as possible!

In the meantime you can view the website at:
https://bootstrap-vue.now.sh/

**Comment by jackmu95** [comment]
The website is back up again
