### ISSUE TITLE
Selected component doesn't highlight in sidebar navigation

### ISSUE THREAD

**Issue by kushalpandya** [bootstrap-vue/bootstrap-vue.github.io#3]
I select `Dropdowns` component, and page loaded for the same but it doesn't highlight the same on right side nav.
![screenshot from 2016-12-28 12-36-48](https://cloud.githubusercontent.com/assets/1748044/21515996/5de9a11c-ccfa-11e6-82c5-c23ab55e5cd3.png)

**Comment by pi0** [comment]
Hey @kushalpandya  Docs are now much better :)
